baseurl: "/"
permalink: pretty
title: "Idea Bosque"

# Logo configuration
logo:
  mobile: "images/logo/logo.svg"
  mobile_height: "48px"
  mobile_width: "auto"
  desktop: "images/logo/logo.svg"
  desktop_height: "48px"
  desktop_width: "auto"

# Home page configuration
home: 
  limit_services: 6

# Collection Configuration
collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  solutions:
    output: true
    sort_by: order  # Sorting solutions by order defined in markdown files

# Default layout settings
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "solutions"
    values:
      layout: "solution"

# Sass (SCSS) configuration
sass:
  style: compressed

# Plugins configuration
plugins:
  - jekyll-environment-variables

# Files and folders to exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
